corrected indenting
Former-commit-id: d48e20f01ea780caecf53971ff1f010cc61ac995

diff --git a/regression-test b/regression-test
--- a/regression-test
+++ b/regression-test
@@ -142,12 +142,12 @@ if [ ! -z "$CompareFile" ]; then
         fi
     done
     cat $TMPDIR/networks.locking | while read Network1 Network2; do
-	    echo "./sana -g1 $Network1 -g2 $Network2 -lock $OutputDir/$Network1-$Network2.locking -o $OutputDir/$Network1-$Network2-locking-test &> /dev/null"
+	echo "./sana -g1 $Network1 -g2 $Network2 -lock $OutputDir/$Network1-$Network2.locking -o $OutputDir/$Network1-$Network2-locking-test &> /dev/null"
     done | parallel 8
     cat $TMPDIR/networks.locking | while read Network1 Network2; do
 	if [[ `grep -f "$OutputDir/$Network1-$Network2.locking" "$OutputDir/$Network1-$Network2-locking-test.out.align" | wc -l` -ne 50 ]]; then
-	REGRESSION_FAILED=true
-	echo "Locking mechanism regression testing failed on $Network1 and $Network2 on $OutputDir/$Network1-$Network2.locking file" >&2
+	    REGRESSION_FAILED=true
+	    echo "Locking mechanism regression testing failed on $Network1 and $Network2 on $OutputDir/$Network1-$Network2.locking file" >&2
 	fi
     done
 
