add more informative output
Former-commit-id: 78cf6e6daed50efdf8f17021d8957de0ca25162c

diff --git a/regression-test b/regression-test
--- a/regression-test
+++ b/regression-test
@@ -86,7 +86,7 @@ done
 
 IterationsAvg=`echo $Iterations | tr " " "\n" | awk '{s+=$1}END{print s/NR}'`
 IterationsAvg=`printf "%f" $IterationsAvg`
-printf "Iterations Average: %s \n" "$IterationsAvg" >> $OutputFile
+printf "Iterations /s Average: %s \n" "$IterationsAvg" >> $OutputFile
 
 PrintTestScores()
 {
@@ -122,8 +122,8 @@ if [ ! -z "$CompareFile" ]; then
         baseItem=`echo -e $BaseAverages | awk '{print $'$i'}'`
         newItem=`echo -e $NewAverages | awk '{print $'$i'}'`
         name=`echo -e $Names | awk '{print $'$i'}'`
-        errorDif=`parse "($baseItem - $newItem)/$baseItem"`
-        echo $name $errorDif
+        errorDif=`parse "($newItem - $baseItem)/$baseItem"`
+	echo "$name: ($newItem - $baseItem)/$baseItem, changeFrac: $errorDif, margin $ErrorMargin" >&2
         errorDif=`parse "ABS($errorDif)" | awk '{printf "%.16f\n",$1}'`
         if [[ `echo "$errorDif < $ErrorMargin" | bc -l` -eq 0 ]]; then
             REGRESSION_FAILED="true"
@@ -131,7 +131,7 @@ if [ ! -z "$CompareFile" ]; then
         fi
     done
 
-    echo "Checking SANA Locking Mechanism" >> $OutputFile
+    echo "Checking SANA Locking Mechanism" | tee -a $OutputFile
     # First create the shuffled list so we can run them in parallel in the next loop.
     touch $TMPDIR/networks.locking
     for i in `seq 4`; do
@@ -148,7 +148,7 @@ if [ ! -z "$CompareFile" ]; then
         fi
     done
     cat $TMPDIR/networks.locking | while read Network1 Network2; do
-	echo "./sana -g1 $Network1 -g2 $Network2 -lock $OutputDir/$Network1-$Network2.locking -o $OutputDir/$Network1-$Network2-locking-test &> /dev/null"
+	echo "echo checking locking between $Network1 and $Network2 >/dev/tty; ./sana -g1 $Network1 -g2 $Network2 -lock $OutputDir/$Network1-$Network2.locking -o $OutputDir/$Network1-$Network2-locking-test &> /dev/null"
     done | parallel -s bash 8
     cat $TMPDIR/networks.locking | while read Network1 Network2; do
 	if [[ `grep -f "$OutputDir/$Network1-$Network2.locking" "$OutputDir/$Network1-$Network2-locking-test.out.align" | wc -l` -ne 50 ]]; then
