make executables have sana1.1 rather than sana as their basename

diff --git a/regression-tests/BioGRID/regression-test b/regression-tests/BioGRID/regression-test
--- a/regression-tests/BioGRID/regression-test
+++ b/regression-tests/BioGRID/regression-test
@@ -60,10 +60,10 @@ fi
 NL='
 '
 
-[ -x ./sana ] || die "can't find ./sana executable"
+[ -x $SANA_EXE ] || die "can't find $SANA_EXE executable"
 
 # Find out the speed of this machine so we can scale the runtime properly to get repeatable results.
-SPEED=`./sana -s3 1 -g1 RNorvegicus -g2 SPombe -t 0 2>&1 | awk '/getPBad/{++n;s+=$NF}END{print s/n/1e6}'`
+SPEED=`$SANA_EXE -s3 1 -g1 RNorvegicus -g2 SPombe -t 0 2>&1 | awk '/getPBad/{++n;s+=$NF}END{print s/n/1e6}'`
 echo "This host is about a factor $SPEED the speed of the original SANA Jenkins server"
 
 # ordered by size in number of nodes
@@ -71,7 +71,7 @@ nets="`echo RNorvegicus SPombe CElegans MMusculus SCerevisiae AThaliana DMelanog
 export Networks_count=`echo $nets | wc -w`
 #Biogrid_network="$nets" #`echo $nets | newlines | sed 's/$/.el/' | (cd networks; xargs ls -Sr) | sed 's/\.el$//'`
 
-echo "$nets" | awk '{net[NR-1]=$NF}END{for(i=0;i<NR;i++)for(j=i+1;j<NR;j++) printf "echo Running %s-%s; ./sana -usingIterations -t 300 -s3 1 -g1 %s -g2 %s -o '$OutputDir'/%s-%s > '$OutputDir'/%s-%s.progress 2>&1\n",net[i],net[j],net[i],net[j],net[i],net[j],net[i],net[j]}' | eval $PARALLEL
+echo "$nets" | awk '{net[NR-1]=$NF}END{for(i=0;i<NR;i++)for(j=i+1;j<NR;j++) printf "echo Running %s-%s; $SANA_EXE -usingIterations -t 300 -s3 1 -g1 %s -g2 %s -o '$OutputDir'/%s-%s > '$OutputDir'/%s-%s.progress 2>&1\n",net[i],net[j],net[i],net[j],net[i],net[j],net[i],net[j]}' | eval $PARALLEL
 
 Iterations=""
 echo "Checking Iterations Speed" >> $OutputFile
