made sana executable an argument to regression-tests

diff --git a/regression-tests/BioGRID/regression-test b/regression-tests/BioGRID/regression-test
--- a/regression-tests/BioGRID/regression-test
+++ b/regression-tests/BioGRID/regression-test
@@ -65,7 +65,7 @@ fi
 NL='
 '
 
-[ -x ./sana ] || die "can't find ./sana executable"
+[ -x "$SANA_EXE" ] || die "can't find executable '$SANA_EXE'"
 
 # Alphabetical order--not particularly useful
 #nets='AThaliana CElegans DMelanogaster HSapiens MMusculus RNorvegicus SCerevisiae SPombe'
@@ -75,7 +75,7 @@ nets="`echo RNorvegicus SPombe CElegans MMusculus SCerevisiae AThaliana DMelanog
 export Networks_count=`echo $nets | wc -w`
 #Biogrid_network="$nets" #`echo $nets | newlines | sed 's/$/.el/' | (cd networks; xargs ls -Sr) | sed 's/\.el$//'`
 
-echo "$nets" | awk '{net[NR-1]=$NF}END{for(i=0;i<NR;i++)for(j=i+1;j<NR;j++) printf "echo Running %s-%s; ./sana -t 5 -s3 1 -g1 %s -g2 %s -o '$OutputDir'/%s-%s > '$OutputDir'/%s-%s.progress 2>&1\n",net[i],net[j],net[i],net[j],net[i],net[j],net[i],net[j]}' | eval $PARALLEL
+echo "$nets" | awk '{net[NR-1]=$NF}END{for(i=0;i<NR;i++)for(j=i+1;j<NR;j++) printf "echo Running %s-%s; \"'"$SANA_EXE"'\" -t 5 -s3 1 -g1 %s -g2 %s -o '$OutputDir'/%s-%s > '$OutputDir'/%s-%s.progress 2>&1\n",net[i],net[j],net[i],net[j],net[i],net[j],net[i],net[j]}' | eval $PARALLEL
 
 Iterations=""
 echo "Checking Iterations Speed" >> $OutputFile
