added code to NOT remove regression output directory in case of failure

diff --git a/regression-tests/BioGRID/regression-test b/regression-tests/BioGRID/regression-test
--- a/regression-tests/BioGRID/regression-test
+++ b/regression-tests/BioGRID/regression-test
@@ -151,4 +151,8 @@ if [ ! -z "$CompareFile" ]; then
 fi
 
 echo encountered a total of $NUM_FAILS failures
+if [ $NUM_FAILS -gt 0 ]; then
+    trap "" 0
+    echo "Since regression had some failures; directory $TMPDIR is not being erased"
+fi
 exit $NUM_FAILS
