update cpus and add /bin/time to regressions

diff --git a/scripts/cpus b/scripts/cpus
--- a/scripts/cpus
+++ b/scripts/cpus
@@ -1,23 +1,54 @@
 #!/bin/sh
-TMP=/tmp/cpus.$$
-trap "/bin/rm -f $TMP; exit" 0 1 2 3 15
+[ "$MYTMP" = "" ] && MYTMP=/tmp
+TMPDIR=$MYTMP/cpus.$$
+MY_CPUS_USED=$MYTMP/last-cpus-avail-of-$USER
+trap "/bin/rm -rf $TMPDIR; exit" 0 1 2 3 15
+mkdir $TMPDIR
+
+die(){ echo "$USAGE${NL}FATAL ERROR in $BASENAME:" "$@" >&2; exit 1; }
+
+load=0
+[ -f $MY_CPUS_USED ] && myload=`cat $MY_CPUS_USED`
+echo "$myload" | grep '^[0-9][0-9]*$' >/dev/null || myload=0
+VERBOSE=false
+THREADS=false
+while [ $# -gt 0 ]; do
+    case "$1" in
+    -[Tt]*) THREADS=true; shift;; # count threads instead of physical cores
+    -[Vv]*) VERBOSE=true; shift;;
+    avail*) uptime > $TMPDIR/uptime
+	load=`cat $TMPDIR/uptime | sed 's/.*load averages*://' -e 's/,//g' | newlines |
+	    awk 'BEGIN{load=999999}{if(1*$1<load)load=1*$1}END{printf "%d\n", load}'`
+	$VERBOSE && (cat $TMPDIR/uptime; echo $load is uptime load, and my avail was most recently $myload) >&2
+	shift
+	;;
+    *) die "unknown option '$1'" ;;
+    esac
+done
+
+if [ -f /proc/cpuinfo ]; then
+    if $THREADS; then
+	grep -c '^processor[ 	]*:' /proc/cpuinfo
+    else
+	grep '^cpu cores[ 	]*:' /proc/cpuinfo | uniq | awk '{print $NF}END{exit(NR-1)}' || die "incorrect parsing of /proc/cpuinfo"
+    fi
+    exit 0
+fi
+
+output(){ [ -f $TMPDIR/cpus ] && awk '{cpus=$1; av=(cpus-int('"$load"')+0*int('"$myload"')); printf "%d\n", (av<0)?0:av}' $TMPDIR/cpus | tee $MY_CPUS_USED && exit 0; }
 
 # Most Linux machines:
-lscpu >$TMP 2>/dev/null && awk '/^CPU[(s)]*:/{cpus=$NF}END{if(cpus)print cpus; else exit 1}' $TMP && exit
+lscpu >$TMPDIR/lscpu 2>/dev/null &&
+    awk '/^CPU[(s)]*:/{cpus=$NF}END{if(cpus)print cpus; else exit 1}' $TMPDIR/lscpu > $TMPDIR/cpus && output
 
 # MacOS:
-([ `arch` = Darwin -o `uname` = Darwin ] || uname -a | grep Darwin >/dev/null) && sysctl -n hw.ncpu && exit
+(arch;uname -a) | egrep 'Darwin|arm64' >/dev/null && sysctl -n hw.ncpu > $TMPDIR/cpus && output
 
 # Cygwin:
-case `arch` in
-CYGWIN*) grep -c '^processor[ 	]*:' /proc/cpuinfo; exit ;;
-*) if [ -d /dev/cpu -a ! -f /dev/cpu/microcode ]; then
-    ls -F /dev/cpu | fgrep -c
-    exit
-   fi
-    ;;
-esac
-
-# Oops
-echo "couldn't figure out number of CPUs" >&2; exit 1
-
+if (arch; uname -a) | grep CYGWIN >/dev/null; then
+    die "shouldn't get here since CYGWIN has /proc/cpuinfo" #grep '^cpu cores[ 	]*:' /proc/cpuinfo | uniq | awk '{print $NF}'
+elif [ -d /dev/cpu -a ! -f /dev/cpu/microcode ]; then
+    ls -F /dev/cpu | fgrep -c > $TMPDIR/cpus && output
+else
+    echo "couldn't figure out number of CPUs" >&2; exit 1
+fi
