generalized CYGWIN detection in cpu counting

diff --git a/scripts/cpus b/scripts/cpus
--- a/scripts/cpus
+++ b/scripts/cpus
@@ -34,14 +34,10 @@ lscpu >$TMPDIR/lscpu 2>/dev/null &&
     sysctl -n hw.ncpu > $TMPDIR/cpus && output
 
 # Cygwin:
-case `arch` in
-CYGWIN*) grep -c '^processor[ 	]*:' /proc/cpuinfo; exit ;;
-*) if [ -d /dev/cpu -a ! -f /dev/cpu/microcode ]; then
+if (arch; uname -i) | grep CYGWIN >/dev/null; then
+    grep -c '^processor[ 	]*:' /proc/cpuinfo
+elif [ -d /dev/cpu -a ! -f /dev/cpu/microcode ]; then
     ls -F /dev/cpu | fgrep -c > $TMPDIR/cpus && output
-   fi
-    ;;
-esac
-
-# Oops
-echo "couldn't figure out number of CPUs" >&2; exit 1
-
+else
+    echo "couldn't figure out number of CPUs" >&2; exit 1
+fi
