use lscpu to determine cores if possible

diff --git a/scripts/cpus b/scripts/cpus
--- a/scripts/cpus
+++ b/scripts/cpus
@@ -1,7 +1,9 @@
 #!/bin/sh
-[ -d /dev/cpu ] && ls -F /dev/cpu | fgrep -c /
-([ `arch` = Darwin -o `uname` = Darwin ] || uname -a | grep Darwin >/dev/null) && sysctl -n hw.ncpu
-
+(lscpu | awk '/^CPU[(s)]*:/{print $NF}') 2>/dev/null && exit
+([ `arch` = Darwin -o `uname` = Darwin ] || uname -a | grep Darwin >/dev/null) && sysctl -n hw.ncpu && exit
 case `arch` in
 CYGWIN*) grep -c '^processor[ 	]*:' /proc/cpuinfo ;;
+*) [ -d /dev/cpu -a ! -f /dev/cpu/microcode ] && ls -F /dev/cpu | fgrep -c / && exit;;
 esac
+echo "couldn't figure out number of CPUs" >&2; exit 1
+
