fix newlines use of awk

diff --git a/scripts/newlines b/scripts/newlines
--- a/scripts/newlines
+++ b/scripts/newlines
@@ -1,2 +1,5 @@
 #!/bin/sh
-/bin/awk '{for(i=1; i<=NF; i++) print $i}' "$@"
+[ -x /bin/awk ] && exec /bin/awk '{for(i=1; i<=NF; i++) print $i}' "$@"
+[ -x /usr/bin/awk ] && exec /usr/bin/awk '{for(i=1; i<=NF; i++) print $i}' "$@"
+echo "can't find an awk" > &2
+exit 1
